version: 0.2

phases:
  build:
    commands:
      - echo Ejecutar comando de validate-template
      - cd talleres/07
      - aws cloudformation validate-template --template-body file://api-cfn-pipeline.yaml

artifacts:
  # Archivos a exportar
  files:
    - 'talleres/07/api-cfn-pipeline.yaml'
  discard-paths: yes
